version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: irving
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ecommerce
     
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  node:
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_USER: irving
      DB_PASSWORD: password123
      DB_NAME: ecommerce
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
